### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:116

### ISSUE THREAD

**Issue by victor123499** [meetshah1995/pytorch-semseg#158]
File "train.py", line 172, in train
    loss = multi_scale_cross_entropy2d(input=outputs, target=labels, device = device)
  File "/home/victor/catkin_ws/src/semantic_slam/semantic_cloud/include/ptsemseg/loss.py", line 75, in multi_scale_cross_entropy2d
    loss = loss + scale_weight[i] * cross_entropy2d(input=inp, target=target, weight=weight, size_average=size_average)
  File "/home/victor/catkin_ws/src/semantic_slam/semantic_cloud/include/ptsemseg/loss.py", line 30, in cross_entropy2d
    weight=weight, size_average=False)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1332, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:116

can anyone help me to solve this probelm?

**Comment by erichhhhho** [comment]
check the target is between 0 - N-1

**Comment by zaidzidane** [comment]
is the issue solved ???... I changed the loss.py in which the ignore_index is changed t0 250.
