### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by SonwYang** [meetshah1995/pytorch-semseg#215]
The details of error are as follows:
`RUNDIR: runs\seg_pascal\59030
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    train(cfg, writer, logger)
  File "train.py", line 72, in train
    model = get_model(cfg["model"], n_classes).to(device)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 386, in to
    return self._apply(convert)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    module._apply(fn)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    module._apply(fn)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 199, in _apply
    param.data = fn(param.data)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error`
My config is:
`model:
    arch: fcn8s
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 256
    img_cols: 256
    path: ./datasets/
training:
    train_iters: 1000
    batch_size: 1
    val_interval: 10
    n_workers: 4
    print_interval: 1
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
        name: 'multi_step'
        milestones: [300,600]
        gamma: 0.1
    resume: null`
How can I solve this problem? Thank you

**Comment by SonwYang** [comment]
I can run this code by cpu, but it reports mistakes when I choose gpu. I think my cuda is normal  because I have do some regular methods to verify it and it works.

**Comment by Aurevious** [comment]
> I can run this code by cpu, but it reports mistakes when I choose gpu. I think my cuda is normal  because I have do some regular methods to verify it and it works.

Hi,have you solve this problem?thank you!
