### ISSUE TITLE
ade20k training error

### ISSUE THREAD

**Issue by Yakirbe** [meetshah1995/pytorch-semseg#3]
File "/home/yakir/git/pytorch-semseg/train.py", line 107, in <module>
    train(args)

  File "/home/yakir/git/pytorch-semseg/train.py", line 61, in train
    loss = cross_entropy2d(outputs, labels, size_average=True)

  File "ptsemseg/loss.py", line 18, in cross_entropy2d
    loss /= mask.data.sum()

RuntimeError: cuda runtime error (59) : device-side assert triggered at /home/soumith/local/builder/wheel/pytorch-src/torch/lib/THC/generated/../generic/THCTensorMathReduce.cu:262

any idea what this is about?

**Comment by josephreisinger** [comment]
I ran into this too. The cuda error is misleading, basically it's saying that *something* happened on the device but we're not really sure what (see, e.g.: https://github.com/torch/cutorch/issues/708). 

So anyway, if you try running on CPU you'll get:

```
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    train(args)
  File "train.py", line 62, in train
    loss = cross_entropy2d(outputs, labels)
  File "/home/ubuntu/pytorch-semseg/ptsemseg/loss.py", line 16, in cross_entropy2d
    loss = F.nll_loss(log_p, target, weight=weight, size_average=False)
  File "/home/ubuntu/pytorch-semseg/venv/local/lib/python2.7/site-packages/torch/nn/functional.py", line 501, in nll_loss
    return f(input, target)
  File "/home/ubuntu/pytorch-semseg/venv/local/lib/python2.7/site-packages/torch/nn/_functions/thnn/auto.py", line 41, in forward
    output, *self.additional_args)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /b/wheel/pytorch-src/torch/lib/THNN/generic/ClassNLLCriterion.c:57
```
which is a bit more informative. Basically it's saying that the class target is out of bounds. I'm seeing class labels as high as 208 (there should only be 150).

So the segmentation map loader code is probably incorrect.

**Comment by meetshah1995** [comment]
I roughly followed http://groups.csail.mit.edu/vision/datasets/ADE20K/code/loadAde20K.m to convert the segmentation images (RBG) to segmentation masks (single channel). 

Would be great to add a sanity check like: 

`assert lbl.max() < self.n_classes` in each dataloader class.

Will look into it over the weekend.

**Comment by gaussfan** [comment]
I have encountered with the same problem. And then I found dataset from http://groups.csail.mit.edu/vision/datasets/ADE20K/ and dataset from  http://sceneparsing.csail.mit.edu/  is a little different. The former has more than 150 classes, and the latter is probably what @meetshah1995 suppose to use, with 151 classes, including the background class.

Download the datasets from http://sceneparsing.csail.mit.edu/, with a few code change in config.json and ade20k_loader.py, the problem is solved. The new ade20k_loader.py are as follows.

`class ADE20KLoader(data.Dataset):
    def __init__(self, root, split="training", is_transform=False, img_size=512):
        self.root = root
        self.split = split
        self.is_transform = is_transform
        self.n_classes = 151
        self.img_size = img_size if isinstance(img_size, tuple) else (img_size, img_size)
        self.mean = np.array([104.00699, 116.66877, 122.67892])
        self.files = collections.defaultdict(list)

        for split in ["training", "validation",]:
            file_list = recursive_glob(rootdir=self.root + 'images/' + self.split + '/', suffix='.jpg')
            self.files[split] = file_list

    def __len__(self):
        return len(self.files[self.split])

    def __getitem__(self, index):
        img_path = self.files[self.split][index].rstrip()
        lbl_path = img_path.replace("/images/","/annotations/")[:-4]+".png"

        img = m.imread(img_path)
        img = np.array(img, dtype=np.uint8)

        lbl = m.imread(lbl_path)
        lbl = np.array(lbl, dtype=np.int32)

        if self.is_transform:
            img, lbl = self.transform(img, lbl)
        return img, lbl

   def transform(self, img, lbl):
        if len(img.shape)==2:
            img = img[:,:,np.newaxis]
            img = np.concatenate((img,img,img),axis=2)
        else:
            img = img[:, :, ::-1]
        img = img.astype(np.float64)
        img -= self.mean
        img = m.imresize(img, (self.img_size[0], self.img_size[1]))
        # Resize scales images from 0 to 255, thus we need
        # to divide by 255.0
        img = img.astype(float) / 255.0
        # NHWC -> NCWH
        img = img.transpose(2, 0, 1)

        # lbl = self.encode_segmap(lbl)
        # classes = np.unique(lbl)
        # lbl = lbl.astype(float)
        lbl = m.imresize(lbl, (self.img_size[0], self.img_size[1]), 'nearest', mode='F')
        lbl = lbl.astype(int)
        # assert(np.all(classes == np.unique(lbl)))

        img = torch.from_numpy(img).float()
        lbl = torch.from_numpy(lbl).long()
        return img, lbl
`

**Comment by gaussfan** [comment]
I have encountered with the same problem. And then I found dataset from http://groups.csail.mit.edu/vision/datasets/ADE20K/ and dataset from http://sceneparsing.csail.mit.edu/ is a little different. The former has more than 150 classes, and the latter is probably what @meetshah1995 suppose to use, with 151 classes, including the background class.

Download the datasets from http://sceneparsing.csail.mit.edu/, with a few code change in config.json and ade20k_loader.py, the problem is solved. The new ade20k_loader.py are as follows.

```
class ADE20KLoader(data.Dataset):
    def __init__(self, root, split="training", is_transform=False, img_size=512):
        self.root = root
        self.split = split
        self.is_transform = is_transform
        self.n_classes = 151
        self.img_size = img_size if isinstance(img_size, tuple) else (img_size, img_size)
        self.mean = np.array([104.00699, 116.66877, 122.67892])
        self.files = collections.defaultdict(list)

        for split in ["training", "validation",]:
            file_list = recursive_glob(rootdir=self.root + 'images/' + self.split + '/', suffix='.jpg')
            self.files[split] = file_list

    def __len__(self):
        return len(self.files[self.split])

    def __getitem__(self, index):
        img_path = self.files[self.split][index].rstrip()
        lbl_path = img_path.replace("/images/","/annotations/")[:-4]+".png"

        img = m.imread(img_path)
        img = np.array(img, dtype=np.uint8)

        lbl = m.imread(lbl_path)
        lbl = np.array(lbl, dtype=np.int32)

        if self.is_transform:
            img, lbl = self.transform(img, lbl)
        return img, lbl

   def transform(self, img, lbl):
        if len(img.shape)==2:
            img = img[:,:,np.newaxis]
            img = np.concatenate((img,img,img),axis=2)
        else:
            img = img[:, :, ::-1]
        img = img.astype(np.float64)
        img -= self.mean
        img = m.imresize(img, (self.img_size[0], self.img_size[1]))
        # Resize scales images from 0 to 255, thus we need
        # to divide by 255.0
        img = img.astype(float) / 255.0
        # NHWC -> NCWH
        img = img.transpose(2, 0, 1)

        # lbl = self.encode_segmap(lbl)
        # classes = np.unique(lbl)
        # lbl = lbl.astype(float)
        lbl = m.imresize(lbl, (self.img_size[0], self.img_size[1]), 'nearest', mode='F')
        lbl = lbl.astype(int)
        # assert(np.all(classes == np.unique(lbl)))

        img = torch.from_numpy(img).float()
        lbl = torch.from_numpy(lbl).long()
        return img, lbl
```

**Comment by MSiam** [comment]
@meetshah1995 thanks for the code. I just wanted to mention that line 97 in ade20k loader in encode_segmap method will corrupt the labels since the full ADE20k is not only 150 classes, it has 3148 classes also n_classes will change accordingly. I have uploaded the [class_labels](https://github.com/MSiam/AdaptiveMaskedProxies/blob/master/datasets/ade20k_classes.txt) corresponding to each class_index-1 here as well if it is useful. So if the code is intended to the full dataset it needs to be int64. Otherwise the whole loader structure will be changed to what was posted here to load the earlier version of ADE20k in scene parsing challenge.
